const express = require('express');
const mongoose = require('mongoose');
const router = express.Router();
const jwt = require('jsonwebtoken');
const User = require('../models/User');
const Tenant = require('../models/Tenant');
const RegistrationCode = require('../models/RegistrationCode');
const crypto = require('crypto');
const auth = require('../middleware/auth');
const { isEmail, isStrongEnoughPassword, cleanString } = require('../utils/validation');

function issueToken(user) {
  if (!process.env.JWT_SECRET || process.env.JWT_SECRET.length < 32) {
    const e = new Error('JWT_SECRET غير مضبوط أو ضعيف');
    e.status = 500;
    throw e;
  }
  return jwt.sign({
    id: String(user._id),
    email: user.email,
    name: user.name,
    role: user.role,
    tenantId: user.tenantId ? String(user.tenantId) : null,
  }, process.env.JWT_SECRET, { expiresIn: process.env.JWT_EXPIRES_IN || '7d' });
}

async function resolveTenant() {
  const key = String(process.env.DEFAULT_TENANT_KEY || 'default-school').toLowerCase();
  return Tenant.findOne({ key });
}

// Public endpoint used by the registration form to let parents choose their active institution.
// Only non-sensitive institution fields are exposed.
router.get('/tenants', async (req, res) => {
  try {
    const tenants = await Tenant.find({ isActive: true })
      .select('_id name key')
      .sort({ name: 1 })
      .lean();
    res.json({ tenants });
  } catch (err) {
    console.error('Public tenants list error:', err);
    res.status(500).json({ message: 'تعذر تحميل قائمة المؤسسات' });
  }
});

router.post('/register', async (req, res) => {
  try {
    const name = cleanString(req.body.name, 120);
    const email = cleanString(req.body.email, 320).toLowerCase();
    const password = req.body.password;
    const phone = cleanString(req.body.phone, 40);
    const requestedRole = String(req.body.role || 'parent').trim().toLowerCase();
    const registrationCode = cleanString(req.body.registrationCode, 100);
    const tenantId = cleanString(req.body.tenantId, 100);

    if (!name || !isEmail(email) || !isStrongEnoughPassword(password) || !phone) {
      return res.status(400).json({ message: 'بيانات التسجيل غير صالحة' });
    }

    // Public registration intentionally exposes only parent and admin.
    // super_admin can never be created through this endpoint.
    if (!['parent', 'admin'].includes(requestedRole)) {
      return res.status(400).json({ message: 'نوع الحساب غير مسموح' });
    }

    const existingUser = await User.findOne({ email });
    if (existingUser) return res.status(409).json({ message: 'البريد الإلكتروني مستخدم بالفعل' });

    if (requestedRole === 'parent') {
      if (!tenantId || !mongoose.isValidObjectId(tenantId)) {
        return res.status(400).json({ message: 'اختر المؤسسة التي يتبع لها ولي الأمر' });
      }

      const tenant = await Tenant.findOne({ _id: tenantId, isActive: true });
      if (!tenant) {
        return res.status(400).json({ message: 'المؤسسة المختارة غير موجودة أو غير مفعلة' });
      }

      const user = await User.create({
        name, email, password, phone, role: 'parent', tenantId: tenant._id,
      });

      const token = issueToken(user);
      return res.status(201).json({ token, user: user.toSafeJSON() });
    }

    // Admin/staff registration is allowed only with an active institution
    // registration code generated by a Super Admin.
    if (!registrationCode) {
      return res.status(400).json({ message: 'رمز تسجيل المؤسسة مطلوب لإنشاء حساب مدير/موظف' });
    }

    const normalizedCode = registrationCode.replace(/[^a-zA-Z0-9]/g, '').toUpperCase();
    if (normalizedCode.length < 12 || normalizedCode.length > 80) {
      return res.status(400).json({ message: 'رمز تسجيل المؤسسة غير صالح' });
    }

    const codeHash = crypto.createHash('sha256').update(normalizedCode).digest('hex');
    const registration = await RegistrationCode.findOne({ codeHash }).select('+codeHash');

    if (!registration || !registration.isActive) {
      return res.status(403).json({ message: 'رمز تسجيل المؤسسة غير صالح أو غير مفعل' });
    }

    if (registration.expiresAt && registration.expiresAt.getTime() <= Date.now()) {
      return res.status(403).json({ message: 'انتهت صلاحية رمز تسجيل المؤسسة' });
    }

    if (registration.maxUses > 0 && registration.uses >= registration.maxUses) {
      return res.status(403).json({ message: 'تم استنفاد عدد استخدامات رمز المؤسسة' });
    }

    const tenant = await Tenant.findById(registration.tenantId);
    if (!tenant || !tenant.isActive) {
      return res.status(403).json({ message: 'المؤسسة المرتبطة بالرمز غير متاحة' });
    }

    const user = await User.create({
      name, email, password, phone, role: 'admin', tenantId: tenant._id,
    });

    // Keep usage tracking simple and safe. A maxUses value of 0 means unlimited.
    await RegistrationCode.updateOne(
      { _id: registration._id },
      { $inc: { uses: 1 }, $set: { updatedAt: new Date() } }
    );

    const token = issueToken(user);
    return res.status(201).json({ token, user: user.toSafeJSON() });
  } catch (err) {
    console.error('Registration error:', err);
    res.status(err.status || 500).json({ message: err.message });
  }
});

router.post('/login', async (req, res) => {
  try {
    const email = cleanString(req.body.email, 320).toLowerCase();
    const password = req.body.password;
    if (!isEmail(email) || typeof password !== 'string') {
      return res.status(400).json({ message: 'بيانات الدخول غير صالحة' });
    }

    const user = await User.findOne({ email });
    if (!user || !(await user.comparePassword(password))) {
      return res.status(401).json({ message: 'بريد إلكتروني أو كلمة مرور خاطئة' });
    }

    // Legacy safety: assign users without a tenant to the default tenant.
    if (!user.tenantId) {
      const tenant = await resolveTenant();
      if (tenant) {
        user.tenantId = tenant._id;
        await user.save();
      }
    }

    const token = issueToken(user);
    res.json({ token, user: user.toSafeJSON() });
  } catch (err) {
    console.error('Login error:', err);
    res.status(500).json({ message: 'حدث خطأ أثناء تسجيل الدخول' });
  }
});

router.get('/me', auth, async (req, res) => {
  const user = await User.findById(req.user.id);
  if (!user) return res.status(404).json({ message: 'المستخدم غير موجود' });
  res.json({ user: user.toSafeJSON() });
});

module.exports = router;
